<?php

namespace Donato\OIDCBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * IdentityProviderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IdentityProviderRepository extends EntityRepository
{
}
