vpr:
    resource: "@PROCERGSVPRCoreBundle/Controller/"
    type: annotation

vpr_person:
    prefix:   /person
    resource: "@PROCERGSVPRCoreBundle/Controller/PersonController.php"
    type:     annotation

# API
vpr_api:
    resource: "@PROCERGSVPRCoreBundle/Controller/APIController.php"
    defaults: { _format: json }
    type:     annotation
    prefix:   /

#Admin
vpr_admin:
    resource: "@PROCERGSVPRCoreBundle/Controller/Admin/DefaultController.php"
    type:     annotation
    prefix:   /admin

vpr_admin_poll:
    resource: "@PROCERGSVPRCoreBundle/Controller/Admin/PollController.php"
    type:     annotation
    prefix:   /admin/poll

vpr_admin_ballotbox:
    resource: "@PROCERGSVPRCoreBundle/Controller/Admin/BallotBoxController.php"
    type:     annotation
    prefix:   /admin/ballotbox

vpr_admin_step:
    resource: "@PROCERGSVPRCoreBundle/Controller/Admin/StepController.php"
    type:     annotation
    prefix:   /admin/step

vpr_admin_category:
    resource: "@PROCERGSVPRCoreBundle/Controller/Admin/CategoryController.php"
    type:     annotation
    prefix:   /admin/category

vpr_admin_person:
    resource: "@PROCERGSVPRCoreBundle/Controller/Admin/PersonController.php"
    type:     annotation
    prefix:   /admin/person

vpr_admin_poll_option:
    resource: "@PROCERGSVPRCoreBundle/Controller/Admin/PollOptionController.php"
    type:     annotation
    prefix:   /admin/poll_option
