vpr:
    resource: "@PROCERGSVPRCoreBundle/Controller/"
    type: annotation

procergsvpr_core_homepage:
    pattern:  /
    defaults: { _controller: PROCERGSVPRCoreBundle:Default:index }

procergsvpr_core_oddregister:
    pattern:  /register
    defaults: { _controller: PROCERGSVPRCoreBundle:Default:register }

vpr_person:
    prefix:   /person
    resource: "@PROCERGSVPRCoreBundle/Controller/PersonController.php"
    type:     annotation

#Admin
vpr_admin:
    resource: "@PROCERGSVPRCoreBundle/Controller/Admin/DefaultController.php"
    type:     annotation
    prefix:   /admin

vpr_admin_poll:
    resource: "@PROCERGSVPRCoreBundle/Controller/Admin/PollController.php"
    type:     annotation
    prefix:   /admin/poll

vpr_admin_ballotbox:
    resource: "@PROCERGSVPRCoreBundle/Controller/Admin/BallotBoxController.php"
    type:     annotation
    prefix:   /admin/ballotbox

vpr_admin_step:
    resource: "@PROCERGSVPRCoreBundle/Controller/Admin/StepController.php"
    type:     annotation
    prefix:   /admin/step

vpr_admin_category:
    resource: "@PROCERGSVPRCoreBundle/Controller/Admin/CategoryController.php"
    type:     annotation
    prefix:   /admin/category

vpr_admin_person:
    resource: "@PROCERGSVPRCoreBundle/Controller/Admin/PersonController.php"
    type:     annotation
    prefix:   /admin/person

vpr_admin_poll_option:
    resource: "@PROCERGSVPRCoreBundle/Controller/Admin/PollOptionController.php"
    type:     annotation
    prefix:   /admin/poll_option

procergsvpr_core_municipio:
    pattern:  /municipio
    defaults: { _controller: PROCERGSVPRCoreBundle:Default:municipio }

procergsvpr_core_end:
    pattern:  /end
    defaults: { _controller: PROCERGSVPRCoreBundle:Default:end }

procergsvpr_core_tituloVotou:
    pattern:  /end/change/offer
    defaults: { _controller: PROCERGSVPRCoreBundle:Default:endChangeOffer }

procergsvpr_core_end_change:
    pattern:  /end/change
    defaults: { _controller: PROCERGSVPRCoreBundle:Default:endChange }

procergsvpr_core_end_change_puny:
    pattern:  /end/change/puny
    defaults: { _controller: PROCERGSVPRCoreBundle:Default:endChangePuny }

procergsvpr_core_horarioEncerrado:
    pattern:  /end/timeover
    defaults: { _controller: PROCERGSVPRCoreBundle:Default:endTimeOver }

procergsvpr_core_reforcar_voto:
    pattern:  /reinforce
    defaults: { _controller: PROCERGSVPRCoreBundle:Default:reinforce }

procergsvpr_core_nfgFraca:
    pattern:  /reinforce/puny
    defaults: { _controller: PROCERGSVPRCoreBundle:Default:reinforcePuny }

procergsvpr_core_solicita_titulo:
    pattern:  /reinforce/doc
    defaults: { _controller: PROCERGSVPRCoreBundle:Default:reinforceDoc }

procergsvpr_core_sem_nfg:
    pattern:  /reinforce/offer
    defaults: { _controller: PROCERGSVPRCoreBundle:Default:reinforceOffer }