procergsvpr_core_homepage:
    pattern:  /
    defaults: { _controller: PROCERGSVPRCoreBundle:Default:index }

vpr_person:
    prefix:   /person
    resource: "@PROCERGSVPRCoreBundle/Controller/PersonController.php"
    type:     annotation

#Admin
vpr_admin_poll:
    resource: "@PROCERGSVPRCoreBundle/Controller/Admin/PollController.php"
    type:     annotation
    prefix:   /admin/poll

vpr_admin_ballotbox:
    resource: "@PROCERGSVPRCoreBundle/Controller/Admin/BallotBoxController.php"
    type:     annotation
    prefix:   /admin/ballotbox

vpr_admin_step:
    resource: "@PROCERGSVPRCoreBundle/Controller/Admin/StepController.php"
    type:     annotation
    prefix:   /admin/step

vpr_admin_category:
    resource: "@PROCERGSVPRCoreBundle/Controller/Admin/CategoryController.php"
    type:     annotation
    prefix:   /admin/category

procergsvpr_core_municipio:
    pattern:  /municipio
    defaults: { _controller: PROCERGSVPRCoreBundle:Default:municipio }


procergsvpr_core_tituloVotou:
    pattern:  /tituloVotou
    defaults:
        _controller: FrameworkBundle:Template:template
        template:    'PROCERGSVPRCoreBundle:Default:tituloVotou.html.twig'

procergsvpr_core_nfgFraca:
    pattern:  /nfgFraca
    defaults:
        _controller: FrameworkBundle:Template:template
        template:    'PROCERGSVPRCoreBundle:Default:nfgFraca.html.twig'

procergsvpr_core_horarioEncerrado:
    pattern:  /horarioEncerrado
    defaults:
        _controller: FrameworkBundle:Template:template
        template:    'PROCERGSVPRCoreBundle:Default:horarioEncerrado.html.twig'

procergsvpr_core_cedula:
    pattern:  /cedula
    defaults:
        _controller: FrameworkBundle:Template:template
        template:    'PROCERGSVPRCoreBundle:Default:cedula.html.twig'

procergsvpr_core_solicita_titulo:
    pattern:  /solicita_titulo
    defaults:
        _controller: FrameworkBundle:Template:template
        template:    'PROCERGSVPRCoreBundle:Default:solicita_titulo.html.twig'

procergsvpr_core_reforcar_voto:
    pattern:  /reforcar_voto
    defaults:
        _controller: FrameworkBundle:Template:template
        template:    'PROCERGSVPRCoreBundle:Default:reforcar_voto.html.twig'

procergsvpr_core_sem_nfg:
    pattern:  /sem_nfg
    defaults:
        _controller: FrameworkBundle:Template:template
        template:    'PROCERGSVPRCoreBundle:Default:sem_nfg.html.twig'

procergsvpr_core_places:
    pattern:  /places
    defaults: { _controller: PROCERGSVPRCoreBundle:Default:places }

