<?php

namespace PROCERGS\VPR\CoreBundle\Entity\Sms;

use Doctrine\ORM\EntityRepository;

/**
 * SmsVoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SmsVoteRepository extends EntityRepository
{
    public function getLastSmsId()
    {
        $query = $this->createQueryBuilder('s')
            ->select('MAX(s.smsId)');

        return $query->getQuery()->getSingleScalarResult();
    }
}
